name: C++ CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install C++ compiler and cmake
        run: sudo apt-get update && sudo apt-get install -y g++ cmake

      - name: Compile project and tests
        run: |
          mkdir build
          cd build
          cmake ../src
          cmake --build .

      - name: Run tests
        run: test/testLowlevel.cpp
